<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('DEBUG: My Reports Copy') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="mb-6">
                        <h3 class="text-lg font-medium text-gray-900">DEBUG: My Academic Reports</h3>
                        <p class="text-sm text-gray-600">View your progress reports and assessments</p>
                    </div>

                    @if(isset($reports) && $reports->count() > 0)
                        <div class="space-y-6">
                            @foreach($reports as $report)
                                <div class="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                                    <div class="flex justify-between items-start mb-4">
                                        <div>
                                            <h4 class="text-lg font-semibold text-gray-900">
                                                {{ $report->title ?? 'Progress Report' }}
                                            </h4>
                                            <p class="text-sm text-gray-600">
                                                {{ $report->class->course->name ?? 'Course' }} - {{ $report->class->name ?? 'Class' }}
                                            </p>
                                            <p class="text-sm text-gray-500">
                                                By {{ $report->teacher->name ?? 'Teacher' }} • {{ $report->created_at->diffForHumans() }}
                                            </p>
                                        </div>
                                        <div class="text-right">
                                            <span class="inline-flex px-2 py-1 text-xs rounded-full 
                                                {{ $report->type === 'progress' ? 'bg-green-100 text-green-800' : 'bg-blue-100 text-blue-800' }}">
                                                {{ ucfirst($report->type ?? 'Progress') }}
                                            </span>
                                        </div>
                                    </div>

                                    <div class="mb-4">
                                        <p class="text-gray-700">{{ $report->content }}</p>
                                    </div>

                                    @if(isset($report->progress_percentage))
                                        <div class="mb-4">
                                            <div class="flex justify-between text-sm text-gray-600 mb-1">
                                                <span>Progress</span>
                                                <span>{{ $report->progress_percentage }}%</span>
                                            </div>
                                            <div class="w-full bg-gray-200 rounded-full h-2">
                                                <div class="bg-blue-600 h-2 rounded-full" style="width: {{ $report->progress_percentage }}%"></div>
                                            </div>
                                        </div>
                                    @endif

                                    <div class="flex justify-end">
                                        <button class="text-blue-600 hover:text-blue-800 text-sm font-medium">
                                            View Details
                                        </button>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @else
                        <div class="text-center py-12">
                            <div class="mx-auto w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4">
                                <svg class="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                                </svg>
                            </div>
                            <h3 class="text-lg font-medium text-gray-900 mb-2">No reports available</h3>
                            <p class="text-gray-600">Your academic reports will appear here once they're generated by your teachers.</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout> 